Update pre-push

diff --git a/HookScripts/Python/pre-push b/HookScripts/Python/pre-push
--- a/HookScripts/Python/pre-push
+++ b/HookScripts/Python/pre-push
@@ -1,4 +1,16 @@
 #!/bin/sh
 read local_ref local_sha remote_ref remote_sha
 
-python3 ./.git/hooks/pre-push.py "$local_sha"
+# Check for the Python command
+if command -v python3 &> /dev/null; then
+    PYTHON_CMD="python3"
+elif command -v python &> /dev/null; then
+    PYTHON_CMD="python"
+elif command -v py &> /dev/null; then
+    PYTHON_CMD="py"
+else
+    echo "Python is not installed or not found in PATH!"
+    exit 1
+fi
+
+$PYTHON_CMD ./.git/hooks/pre-push.py "$local_sha"
